apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: gateway
  type: NodePort
  // asdfasdf asdfasdf asdfasdf asdf dsfgasdf asdf asdfa asdfsad asdfasdfasf fasdfas asdfasdfdf
